name: Deploy Databricks Bundle

on:
  push:
    branches:
      - main

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Verify CLI
        run: |
          databricks version

      - name: Check Environment
        run: |
          echo "HOST LENGTH:"
          echo ${#DATABRICKS_HOST}
          echo "TOKEN LENGTH:"  
          echo ${#DATABRICKS_TOKEN}

      - name: Test Authentication
        run: |
          databricks current-user me

      - name: Validate Bundle
        run: |
          databricks bundle validate -t dev

      - name: Deploy Bundle
        run: |
          databricks bundle deploy -t dev
